FROM python:3.7-slim-stretch

WORKDIR /var/task
COPY ./src ./snowalert/src

RUN pip3 install wheel ./snowalert/src/

RUN apt-get update \
&& apt-get install -y r-base vim

RUN R -e "install.packages('dplyr', repos = 'https://cloud.r-project.org')"

CMD ./snowalert/src/sar-azure-login/run.sh
